version: '3'
services:
    app:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            APP_ENV: local
            PHP_IDE_CONFIG: "serverName=dev-test"
        working_dir: /var/www/html
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"
        volumes:
            - ./:/var/www/html
            - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - mynet
        extra_hosts:
            - "host.docker.internal:host-gateway"
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "100m"
                max-file: "10"
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/ssl/:/etc/nginx/ssl/
        networks:
            - mynet
    emergency-database:
        image: mysql:8.1.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
        networks:
            - mynet
networks:
    mynet:
        driver: bridge
